# Starter pipeline


# TODO remove sensitive values

pool:
  vmImage: ubuntu-latest

jobs:

- jobs:
  - job: validate_infrastructure
    displayName: Validate Infrastructure
    steps:

    - script: |
        az bicep build main.bicep
      displayName: 'Compile main.bicep'

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Validate main.bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'udemy-courses(9f53062f-e565-443b-8eb8-63aeb88dc7fd)'
        subscriptionId: '9f53062f-e565-443b-8eb8-63aeb88dc7fd'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'bicep-course'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'main.json'
        deploymentMode: 'Validation'


  - job: deploy_infrastructure
    displayName: Deploy Infrastructure
    steps:

    - script: |
        az bicep build main.bicep
      displayName: 'Compile main.bicep'

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy main.bicep
      dependsOn: validate_infrastructure
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'udemy-courses(9f53062f-e565-443b-8eb8-63aeb88dc7fd)'
        subscriptionId: '9f53062f-e565-443b-8eb8-63aeb88dc7fd'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'bicep-course'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'main.json'
        deploymentMode: 'Incremental'
